# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master

pool:
  vmImage: Hosted VS2017
steps:
  - task: DotNetCoreCLI@2
    displayName: "dotnet restore"
    inputs:
      command: restore
      projects: |
        src/**/*.csproj
        tests/**/*.csproj

  - task: DotNetCoreCLI@2
    displayName: "dotnet build"
    inputs:
      projects: "src/**/*.csproj"

  - task: DotNetCoreCLI@2
    displayName: "dotnet test"
    inputs:
      command: test
      projects: "tests/**/*.csproj"

  - task: DotNetCoreCLI@2
    displayName: "dotnet pack"
    inputs:
      command: pack
      packagesToPack: "src/**/*.csproj"

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: packages"
    inputs:
      ArtifactName: packages
